repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-docstring-first
  - id: detect-private-key
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
- hooks:
  - id: check-json5
  repo: https://gitlab.com/bmares/check-json5
  rev: v1.0.0
- hooks:
  - args:
    - --py311-plus
    files: ^backend/
    id: pyupgrade
  repo: https://github.com/asottile/pyupgrade
  rev: v3.10.1
- hooks:
  - args:
    - --target-version
    - '4.2'
    files: ^backend/
    id: django-upgrade
  repo: https://github.com/adamchainz/django-upgrade
  rev: 1.14.0
- hooks:
  - files: ^backend/
    id: black
  repo: https://github.com/psf/black
  rev: 23.7.0
- hooks:
  - files: ^backend/
    id: isort
  repo: https://github.com/PyCQA/isort
  rev: 5.12.0
- hooks:
  - id: commitizen
  # - id: commitizen-branch
  #   stages:
  #   - push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.9.0
