# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key
-   repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        files: ^backend/
        args: [--py311-plus]
-   repo: https://github.com/adamchainz/django-upgrade
    rev: '1.14.0'
    hooks:
      - id: django-upgrade
        files: ^backend/
        args: ['--target-version', '4.2']
# TODO: Necessita corrigir os erros que o Lint apresentou
# -   repo: https://github.com/Riverside-Healthcare/djLint
#     rev: v1.32.1
#     hooks:
#       - id: djlint-reformat-django
#         files: ^backend/
#       - id: djlint-django
#         files: ^backend/
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        files: ^backend/
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^backend/
