version: "3.6"
services:
  # Database
  database:
    image: postgres:12.3-alpine
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit_manga
    env_file:
    - .env

  memcached:
    image: bitnami/memcached
    environment:
      - MEMCACHED_CACHE_SIZE=256
      - MEMCACHED_THREADS=4
      - MEMCACHED_MAX_ITEM_SIZE=8388608

  backend: &backend
    user: 1000:7018
    image: linea/manga_backend:1.5
    command: /start.sh
    env_file:
      - .env
    depends_on:
       - rabbit
       - database
       - memcached
    volumes:
      - /mnt/lustre_t1_nfs/cl/sdss/manga/mcubes:/usr/src/app/images
      - /mnt/lustre_t1_nfs/cl/sdss/manga/mcubes:/tmp/cache
      - ./log:/log

  celery_worker: &celery_worker
    <<: *backend
    command: /start-celery-worker.sh
    depends_on:
      - backend

  celery_beat: &celery_beat
    <<: *backend
    command: /start-celery-beat.sh
    depends_on:
      - backend

  frontend:
    image: linea/manga_frontend:1.5
    ports:
      - 8080:8080
    volumes:
      - /mnt/lustre_t1_nfs/cl/sdss/manga/mcubes:/var/www/data
    depends_on:
      - backend
