version: "3.6"
services:
  # Database
  database:
    image: postgres:12.3-alpine
    env_file:
      - .env.dev
    expose:
      # Deixar a porta exposta para desenvolvimento
      # isto permite acessar o banco de dados a partir de outros apps como o DBeaver
      - 5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data


  # Backend Django
  backend:
    build: ./backend
    env_file:
      - .env.dev
    volumes:
      - ./backend:/app
      - ./images:/images

  # Frontend React
  frontend:
    # image: node:8.10
    image: node:12.16.2
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: yarn start

  # Servidor Web NGINX
  nginx:
    image: nginx:latest
    # build: ./frontend
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./images:/images
    depends_on:
      - backend
      - frontend