version: "3.6"
services:
  # (Backend Flask)
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./images:/images
  frontend:
    image: node:12.16.2
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: yarn start
  # Servidor Web NGINX
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/development.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend

# version: "3.6"
# services:
#   # (Backend Flask)
#   backend:
#     build: ./backend
#     volumes:
#       - ./backend:/app
#       - ./images:/images
#     # ports:
#     #   - 8000:8000
#   frontend:
#     build: ./frontend
#     ports:
#       - 80:8080
#     volumes:
#       - ./nginx/development.conf:/etc/nginx/conf.d/default.conf:ro
#     # cap_drop:
#     #   - ALL
#     depends_on:
#       - backend
#     links:
#       - backend