version: '3.6'
services:
  # Backend Django
  backend:
    build: ./backend
    env_file:
      - .env.dev
    volumes:
      - ./backend:/app
      - ./images:/images
      - ./log:/log
    depends_on:
      - rabbit
      - database

  # Frontend React
  frontend:
    # image: node:8.10
    image: node:12.16.2
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: yarn start

  # Database
  database:
    image: postgres:13.6-alpine
    env_file:
      - .env.dev
    # expose:
    #   # Deixar a porta exposta para desenvolvimento
    #   # isto permite acessar o banco de dados a partir de outros apps como o DBeaver
    #   - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Servidor Web NGINX
  nginx:
    image: nginx:stable-alpine
    # build: ./frontend
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./images:/images
    depends_on:
      - backend
      - frontend

  # Message-Broker Software RabbitMQ
  rabbit:
    image: rabbitmq:3-management-alpine
    hostname: rabbit_manga
    env_file:
      - .env.dev

volumes:
  postgres-data:
