version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn manga.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/home/app/backend/static
      - ./images:/home/app/backend/images
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.3-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static:/home/app/backend/static
    ports:
      - 1337:80
    depends_on:
      - backend

volumes:
  pg_data:
    driver: local
  static:
    driver: local
