version: "3.6"
services:
  # (Backend Flask)
  backend:
    build: ./backend
    image: manga_backend
    volumes:
      - ./backend:/app
      - ./images:/images
    ports:
      - 8000:8000

  frontend:
    build: ./frontend
    ports:
      - 80:8080
    volumes:
      - ./nginx/development.conf:/etc/nginx/conf.d/default.conf:ro
    # cap_drop:
    #   - ALL
    depends_on:
      - backend
    links:
      - backend