# Generated by Django 3.0.6 on 2020-09-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='megacube',
            field=models.BigIntegerField(blank=True, help_text="The name of the megacube's file", null=True, verbose_name='Megacube File Name'),
        ),
    ]
