# Generated by Django 3.0.7 on 2021-03-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='nsa_z',
            field=models.FloatField(blank=True, help_text='Heliocentric redshift', null=True, verbose_name='Heliocentric Redshift'),
        ),
    ]
