# Generated by Django 3.0.6 on 2020-09-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0002_image_megacube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='megacube',
            field=models.CharField(blank=True, help_text="The name of the megacube's file", max_length=150, null=True, verbose_name='Megacube File Name'),
        ),
    ]
