# Generated by Django 3.0.6 on 2020-09-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0003_auto_20200922_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='mangaid',
            field=models.CharField(help_text='MaNGA ID for this object (e.g. 1-114145)', max_length=100, unique=True, verbose_name='MaNGA ID'),
        ),
        migrations.AlterField(
            model_name='image',
            name='megacube',
            field=models.CharField(help_text="The name of the megacube's file", max_length=150, unique=True, verbose_name='Megacube File Name'),
        ),
        migrations.AlterField(
            model_name='image',
            name='plateifu',
            field=models.CharField(help_text='Plate+ifudesign name for this object (e.g. 7443-12701)', max_length=100, unique=True, verbose_name='Plate IFU Design ID'),
        ),
    ]
