# Generated by Django 3.1.8 on 2023-07-10 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0008_auto_20230710_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='f_He1_5876',
            new_name='f_he1_5876',
        ),
    ]
