# Generated by Django 3.1.8 on 2023-07-10 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0009_auto_20230710_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='fcfc_1_50',
            new_name='fcfc1_50',
        ),
    ]
