# Generated by Django 3.1.8 on 2023-09-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0014_auto_20230831_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='ned_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Common Name'),
        ),
    ]
