"""empty message

Revision ID: 2e1d9b35ae88
Revises: fecb02b0a128
Create Date: 2020-04-30 21:12:49.550209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e1d9b35ae88'
down_revision = 'fecb02b0a128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_galaxy', sa.Integer(), nullable=True),
    sa.Column('content', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['id_galaxy'], ['galaxy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_galaxy', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_galaxy'], ['galaxy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.drop_table('comment')
    # ### end Alembic commands ###
